import React from 'react'
import Head from 'next/head'
const Page2 = () => {
    return (
        <>
        <Head>
        <title>Pages 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <p>ini page 3</p>
        </>
    )
}

export default Page2;